services:
  - type: web
    name: udyam-setu
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build && cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
